### ISSUE TITLE
Some "sudo" missing

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/framaestro_ynh#1]
Hello,
I have tried installing the package but failed because of permissions. It worked when I added sudo to these two lines:
https://github.com/YunoHost-Apps/framaestro_ynh/blob/master/scripts/install#L52-L52 (sudo git clone)

https://github.com/YunoHost-Apps/framaestro_ynh/blob/master/scripts/install#L78 (sudo sed)

Thanks for the package

**Comment by ldidry** [comment]
Hey, don't rush on the package, i'm working on this package from this morning only 😉 

Added your `sudo` though (strange thing: it worked for me without it)

**Comment by scith** [comment]
No worries, I just saw the app on my timeline and wanted to give it a try on my test machine
It works well so far :+1:

**Comment by ldidry** [comment]
There is no togetherjs hub (I don't know its real name) yet, so no mouse movment tracking, no chat and no windows sync.
